twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        appli_version: 'v.%env(APPLI_VERSION)%'
        assets_version: '?v=%env(APPLI_VERSION)%'
